runtime: nodejs14
service: default
instance_class: F2
env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  DB_USER: "trinity"
  DB_PASS: "1234"
  DB_NAME: "trinity"
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
beta_settings: 
  cloud_sql_instances: hallowed-cortex-343019:northamerica-northeast1:trinity